# Generated by Django 4.1.3 on 2023-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("descr", models.TextField()),
                ("current_stats", models.SmallIntegerField(default=0)),
                ("expected_stats", models.SmallIntegerField(default=100)),
            ],
        ),
    ]
